### PR TITLE
chore(package): pin `node-dir` version to retain `node >= 4` support

### LINKED ISSUE #128: [Chore] Recent update of node-dir breaks copy-webpack-plugin
Please, check `4.x.x`  for same issue. https://github.com/fshost/node-dir/issues/50

### PR DESCRIPTION
**Pull request by evanshortiss**
### Notable Changes
---

`node-dir` recently released a new version with breaking changes, but they did not do a major version bump. This means anyone using `copy-webpack-plugin` on node 4 (and maybe 5?) is going to have broken builds.

This will fix it by ensuring the node 4 friendly version is used until they can revert changes.

### Issues
---

- Fixes #128 

> ℹ️  edited by @michael-ciniawsky (Formatting)

### CODE REVIEW

**Comment by evanshortiss** [comment]
Should this be backported to 3.0 too?

**Comment by michael-ciniawsky** [comment]
@evanshortiss Could please rebase to latest `master` before we triage this? Are there better maintained packages then `node-dir` ?

**Comment by d3viant0ne** [comment]
@evanshortiss - I'm not seeing anything in node-dir to indicate that they are increasing the minimum node version to not include node 4.

If there is an issue somewhere, could you post it here?

**Comment by michael-ciniawsky** [comment]
Feel free to reopen

**Pull request closed without merging**
