### PR TITLE
feat: allow async transforms

### PR DESCRIPTION
**Pull request by Perlmint**
Currently implemented a way of the transform is synchronous transform only available. Fixing little makes asynchronous transform available.

### CODE REVIEW

**Comment by matthewmueller** [comment]
+1, this is (unfortunately) needed for things like cssnano

**Comment by kunshao-msft** [comment]
+1 what is the status of this PR?

**Comment by michael-ciniawsky** [comment]
@Perlmint Could you please rebase against current `master` to make reviewing easier ?

**Comment by Perlmint** [comment]
@michael-ciniawsky I just pushed rebased commits!

**Comment by michael-ciniawsky** [comment]
@Perlmint Please sign the CLA by closing and reopening the PR to trigger the CLA Bot again

**Comment by d3viant0ne** [comment]
Bit of housekeeping, this is more an `improvement` than a `bug fix`. I'd prefer to increment the minor version here as this is additional functionality. @michael-ciniawsky @evilebottnawi

**Comment by evilebottnawi** [comment]
@d3viant0ne yes, you are right

**Comment by michael-ciniawsky** [comment]
@Perlmint Could you please rebase one more time, bc of #155. Sry for the inconvenience 😅

**Comment by Perlmint** [comment]
@michael-ciniawsky rebased!

**Comment by SeyfAllahCheref** [comment]
@michael-ciniawsky When the 4.2.0 release is planned please?

**Comment by evilebottnawi** [comment]
@SeyfAllahCheref asap

**Pull request merged**
