### PR TITLE
feat() : Add mandatory pattern

### PR DESCRIPTION
**Pull request by jeffin143**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
#431 

### Breaking Changes
No

### Additional Info
-

### CODE REVIEW

**Comment by dschmidt** [comment]
Hey @jeffin143,

do you plan to finish your PR by adding documentation? It would be really nice to have this feature :-)

**Comment by jeffin143** [comment]
> /cc @jeffin143 maybe we can get more simple name?

Umm does `forced: true` look good ?

**Comment by evilebottnawi** [comment]
@jeffin143 maybe `noErrorOnUnmatchedPattern` and do not emit nor warning nor error?

**Pull request closed without merging**
