### PR TITLE
Improve clarity on how plugin works with built files

### PR DESCRIPTION
**Pull request by soundasleep**
It appears that copy-webpack-plugin is designed to copy files _outside_ of the build process, rather than copy files _created by_ the build process. See: https://github.com/webpack-contrib/copy-webpack-plugin/issues/261

If one uses webpack-copy-plugin to try and copy a built file, if the file did not exist already, then the developer may receive a `WARNING in unable to locate` message, and the file is not correctly copied. This can cause some weird behaviour, especially because if you run webpack again, it will work fine (because it's copied over the previously built file).

I would like to suggest adding in this documentation to the README to prevent people from using the plugin when it's not appropriate for their needs.

This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Can you create minimum reproducible test repo, looks like a bug

**Comment by soundasleep** [comment]
The minimum reproducible thing is:

- a webpack that compiles e.g. index.js -> dist/index.js
- configure copy-webpack-plugin to copy e.g. dist/index.js to dist/index2.js

The first time you run webpack, dist/index.js doesn't exist, so I get a warning that the file doesn't exist. The second time, as long as you haven't cleaned out dist/, the (old) file is copied fine.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo, i can't reproduce you problem

**Comment by evilebottnawi** [comment]
Sorry for delay, see what you mean, you let's merge this in docs

**Comment by evilebottnawi** [comment]
Close in https://github.com/webpack-contrib/copy-webpack-plugin/pull/395, thanks for the PR

**Pull request closed without merging**
