### PR TITLE
chore(package): add `files` property to reduce package size

### PR DESCRIPTION
**Pull request by evilebottnawi**
:star:

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
Use `pkg.files` instead 🙃 ?

**Comment by evilebottnawi** [comment]
@michael-ciniawsky just for this repo (before `webpack-default`), because we have .npmignore :smile:

**Comment by michael-ciniawsky** [comment]
Please use `pkg.files` as it is the cleaner solution for this and reduces the overall package size as a bonus, regardless of `webpack-defaults` or not 🙏

**Comment by evilebottnawi** [comment]
@michael-ciniawsky friendly ping

**Comment by michael-ciniawsky** [comment]
> In the short term, just use `files` (pkg.files)

🙃 You can leave `appveyor.yml` in `.npmignore` if you want, but `files` simply the better solution here

**Comment by evilebottnawi** [comment]
@michael-ciniawsky we migrate to files after `webpack-default`, just little fix :smile: We spend many time on this simple issue :laughing:

**Comment by evilebottnawi** [comment]
@michael-ciniawsky @d3viant0ne rewrite using `files`

**Pull request merged**
