### PR TITLE
docs: remove "$" from copied console line

### PR DESCRIPTION
**Pull request by feisk**
For easy copying of the plugin installation command

This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### CODE REVIEW

**Comment by alexander-akait** [comment]
Why? We use it for any scripts to point what it is script

**Comment by feisk** [comment]
> Why? We use it for any scripts to point what it is script

For consistency of webpack plugin descriptions

**Comment by alexander-akait** [comment]
can you provide example of others?

**Comment by feisk** [comment]
yes, for example here:
https://github.com/webpack-contrib/eslint-webpack-plugin
https://github.com/webpack-contrib/mini-css-extract-plugin

and here https://webpack.js.org/plugins/html-webpack-plugin/
Снимок экрана 2021-01-25 в 14 42 57

When I want to quickly copy the line to install the plugin package, I copy the whole line, in this case it is much easier

**Comment by alexander-akait** [comment]
oh, yes, I see, thanks

**Pull request merged**
