### PR TITLE
chore: update `globby`

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [ ] **bugfix**
- [] new **feature**
- [x] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Update globby

### Breaking Changes

Yes

Some patterns can't be work or work differently (see https://github.com/micromatch/micromatch), some glob options can't be work or work differently (see https://github.com/mrmlnc/fast-glob#compatible-with-node-glob)

### Additional Info

no

### CODE REVIEW

**Comment by oalmali** [comment]
@evilebottnawi Is there any update regarding this? Unfortunately globby 7.1.1 comes with slash 1.0.0 which contains multiple security vulnerabilities.

**Comment by evilebottnawi** [comment]
@oalmali There are bugs in fast-glob on windows, but maybe it is already fixed, need try again

**Comment by patoncrispy** [comment]
Hey all. Just wondering if there has been any movement on this? Our security scans have flagged the `slash` dependency. :(

**Comment by evilebottnawi** [comment]
Will be updated in next release (near future)

**Comment by patoncrispy** [comment]
Any movement on this since June, @evilebottnawi?

**Comment by evilebottnawi** [comment]
@patoncrispy no, major release will be in this month

**Comment by evilebottnawi** [comment]
Done in master, release will be soon

**Pull request closed without merging**
