### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ream88**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [x] **typo fix**
- [ ] **metadata update**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Please accept CLA

**Comment by ream88** [comment]
For what ever reason, I can't sign. Safari complains about `[Error] Cannot load script https://github.githubassets.com/assets/github-bootstrap-e79d5d49.js. Failed integrity metadata check.` and half of GitHub is not usable!

**Comment by evilebottnawi** [comment]
@ream88 try to use other problem

**Comment by ream88** [comment]
done

**Comment by evilebottnawi** [comment]
Thanks all good!

**Pull request merged**
